@echo off
cd /d %~dp0
echo Installing root tools...
npm install
echo Installing frontend...
call npm --prefix frontend install
echo Installing backend...
call npm --prefix backend install
echo Starting AgriLink...
call npm run dev
